### ISSUE TITLE
Explicit fracture model with the pre-processor

### ISSUE THREAD

**Issue by ignasi-p** [NumericalEnvironmental/Facilitator_scripts_for_reactive_flow_through_fractured_rock_with_PHREEQC#1]
First of all, thanks for making this available!
I tested the pre-processor with the data in the following paper:  
Lipson, D.S., McCray, J.E., Thyne, G.D., 2007. Using PHREEQC to simulate solute transport in fractured bedrock.
_Ground water_ **45**, 468-472. https://doi.org/10.1111/j.1745-6584.2007.00318.x

I find the following problems:

 - the description of "w" in file 'DualColumn.py' is wrong. Presumably it should be "width of fracture", or perhaps "fracture aperture".
 - I believe the line `volFrac = A * self.w` should instead be `volFrac = A * 0.5*self.w`, because one should use half the fracture aperture, similarly to the definition of `dxd` . In the model for Lipson et al (2007) this has a negligible effect because the aperture is so thin.
 - in order to obtain the mixing fractions listed in Table 3 of Lipson et al (2007), the lines defining `A`and `volFrac` should be changed to:
 
        A = self.dz * dy *phi
        volFrac = (self.dz * dy) * 0.5*self.w

    I believe that the mixing fractions in Lipson et al (2007) are correct (more or less), because the results of the corresponding Phreeqc simulation using an inert tracer agree reasonably with the equation of:
    Neretnieks (1980) Diffusion in the rock matrix: An important factor in radionuclide retardation? _Journal of Geophysical Research: Solid Earth_ **85**, 4379-4397. https://doi.org/10.1029/JB085iB08p04379

![2007Lipson_5L_200_30-100d](https://github.com/NumericalEnvironmental/Facilitator_scripts_for_reactive_flow_through_fractured_rock_with_PHREEQC/assets/38634677/cc2ff6a6-b2af-4545-95f8-085b25a23d0a)

In the figure the symbols are the Phreeqc calculation and the curves are calculated using the equation from Neretnieks (1980).
In file 'DualColumn.py' I changed the default porosity `phi = 0.2` and `dy = 0.015`, and the following contents for file `grid_params.txt`:

    De	4.40E-10
    nz	200
    nx	5
    dz	0.015
    dx	0.05
    w       0.0004
    dt 	0.0097917
    nShifts	  10213
    alpha 	0.001
    theta 	0.

**Comment by NumericalEnvironmental** [comment]
Thank you VERY much for taking the time to try out this particular script and identifying the issues noted here. Much appreciated!

This is an older script and isn't currently being maintained. I've been relying more on PHAST for reactive transport modeling recently, as opposed to PHREEQC and its more limited transport modeling capabilities. However, I may consider updating this code to use in my PHREEQC/PHAST course at some point. Your insights are duly noted.
